language: node_js
cache: yarn
node_js:
- '10'
script:
- npm test && npm run coverage
deploy:
  provider: npm
  skip_cleanup: true
  email: dirkjanrutten@gmail.com
  api_key:
    secure: Tj9s+BqnSFCSyHydsJgnZ1lpxE5LTxUvYwo7U3e10wyVcDGNrQkkCBAEuVYERkysprLg0yAqbTskUsPnfFG4DMc8LYHluk+RYRqd1AgVcUc0wLGmjV8ZU1dIvp9ijQygc6ftjGU8OKABo8rRN8HF09QTAav9Pj3ubC8+Ryq6Z1IFOI8mI5s06SBYgK95m4b88F684jib5G69EN9VILOV5txKfPuP/K+GmRIpmJkc/aoolu4NIKgaBpMG44lBpdSJs5w5nMypsNf9uMqLGj/AMUtXdEEMXcHZOmMeYrPb8DFc7AAXyFNh0lyeCFP9/R3RiM9ACImpgCY7k1yDDBQRWealkiuap1g0YZ0LC8SZ2bfQPauP8FU+PWXkpWvv2inEVXXBIKLlw98B0mZwT1xfMMjo3mFLjjDzQI9CHasAqvDcnc7yK8DRPPetzwfvtwQo+8ieetl3hxvUiBcxNyVNKB5MmrIEOKwiV1Pur6qm4eeBiplx/AqFmuXqbZdguzhEbImwYueToQT03hfme0nIrudRw6hZhbnvzngmw+NCIO/aY4YNfBxD+pVBv35WTos6rZsGd/v8qAtJ8JDobqlXlR/EPtpyo6FpoDd178KS89lgrU4Rfh9MlavxiU9EnJJmhbTD2gBKk5/+kR4uvw3XRSS77jI/dxem9HRu0OM30PM=
  on:
    tags: true
    branch: master
